### ISSUE TITLE
rename "L1/L2 pay"

### ISSUE THREAD

**Issue by geoknee** [statechannels/SCBridge-Wallet#120]
* although a defensible claim, state channel networks are not "an L2" in a lot of people's minds
* if we deploy onto a rollup, "L1 pay" is actually causing an L2 tx, and "L2 pay" is doing... an L3 tx?

Suggest "on chain pay" / "fast pay" or something like that.

**Comment by lalexgap** [comment]
If we wanted to consider branding this as a cross chain bridge, L2 payment could become `Bridge Funds`

**Comment by lalexgap** [comment]
Some brainstorming

L1:
- On-chain Pay
- Chain Pay
- Chain Transfer
- on-chain transfer

L2:
- Instant Pay
- Instant Transfer
- Bridge Funds
- Quick Pay

**Comment by NiloCK** [comment]
Went with `Chain Pay` and `Bridge Pay` in #181.
