### ISSUE TITLE
L2 Pay doesn't like decimal values

### ISSUE THREAD

**Issue by lalexgap** [statechannels/SCBridge-Wallet#127]
It looks like right now instead of converting 0.05 ETH to wei for L2 pay, we attempt to save 0.05 as a number

<img width="479" alt="image" src="https://github.com/statechannels/SCBridge-Wallet/assets/1620336/f56b4a54-5cd4-4193-896b-7c26bbc7c71e">

**Comment by NiloCK** [comment]
Work from #128 was cherry picked into #123 and merged. Closing.
