### ISSUE TITLE
Figure out how the clients will exchange messages

### ISSUE THREAD

**Issue by geoknee** [statechannels/SCBridge-Wallet#18]
Let's maybe hold off on this until we have something working with "manual message passing in a script" approach.

When that is ready, we could implement something with http.

**Comment by geoknee** [comment]
Leftfield idea: webRTC? (to be discussed). Maybe not.

**Comment by NiloCK** [comment]
Here is a demo of the API I used for speedrun. It could actually be pretty quick and easy to set up for our purposes - three (or whatever) local browsers running in-browser clients who need data pipes between them.

Each `BroadcastChannel` is bidirectional and is named. So `Alice-Irene` can have one pipe, `Irene-Bob` another, etc.

`BroadcastChannel`s work among browser windows that are hosted in the same origin - eg, https://github.com/*, https:/statechannels.org/*, localhost.

[Screencast from 2023-10-13 10:11:16 PM.webm](https://github.com/statechannels/nitro-smart-contract-wallet/assets/10780590/0ba46ba1-a4c4-464c-9885-bf88cfed82ea)

**Comment by geoknee** [comment]
In order to make this work, I think we will need to have a single server for all the frontends. BroadcastChannels need a consistent origin (so we cannot change the port number, for example).

**Comment by NiloCK** [comment]
BroadcastChannels were implemented and merged in #38. Closing this issue in so far as the hackathon is concerned - to be revisited if this code base will live further than a demonstration.
