### ISSUE TITLE
Monitor contract addreses for balance changes

### ISSUE THREAD

**Issue by lalexgap** [statechannels/SCBridge-Wallet#47]

**Comment by lalexgap** [comment]
This probably doesn't have to be part of the `StateChannelWallet` client.

 The UI could just query the balance at the address. We could either monitor for new blocks and check on each new block or just use a simple timer. Due to time constraints, we could probably get away with the UI calling `getBalance` every `x` seconds and ignore listening for new blocks.

**Comment by geoknee** [comment]
We have a method in place to get the balance inside each client. 

The remaining work is to 
* deploy smart contract wallets to hardhat
* get their predictable addresses and wire them up to the UI
* use events / polling / whatever to keep the react state in sync with the chain
